### ISSUE TITLE
"password" als null initialisieren

### ISSUE THREAD

**Issue by EntenKoeniq-OLD** [nSystemz/RageMP-C-Tutorial-NemesusTV#2]
https://github.com/nSystemz/RageMP-C-Tutorial-NemesusTV/blob/accbda9bf1b203b9cc1eecf6ebae450d61518a7d/backend/Tutorial/Tutorial/Datenbank.cs#L136

Die Variable "password" sollte als "null" initialisiert werden da die Abfrage in bcrypt geändert wurde und es zum Fehler kommt sollte das Passwort nicht als null sondern als leerer String initialisiert sein.

**Letzte Änderung an "Bcrypt.cs":**
https://github.com/nSystemz/RageMP-C-Tutorial-NemesusTV/commit/5c31bc9eed3995ec89a5ce7dc92abef6583a8203#diff-5bdb8300ab2067420fe80c77d01ec1c53eb3a47bf7fdd2c32e9b0130e5d5424f

**Letzte Fehlermeldung von einem Benutzer auf Discord:**
<img src="https://media.discordapp.net/attachments/896524514144444416/896525215138451466/Screenshot_2021-10-10_003055.png" />

**Comment by nSystemz** [comment]
Danke für die Meldung, wird angepasst.
